services:
  db:
    image: postgres
    ports:
      - "5435:5432"
    container_name: courses_service_db
    environment:
      POSTGRES_USER: dumi
      POSTGRES_PASSWORD: dumi
      POSTGRES_DB: courses-service-db
